# Generated by Django 5.1 on 2024-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
