services:
  talk2:
    container_name: talk2
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    command: >
      sh -c "python3 /app/manage.py runserver 0:8000 & 
      celery -A talk2 worker  -B -l info"
    depends_on:
      - redis

  redis:
    container_name: talk2_redis
    image: redis:7.0.8
    restart: always
    volumes:
      - talk2_redis_data:/data
#    ports:
#      - 6379:6379
    expose:
      - "6379"

volumes:
  talk2_redis_data:
