# Generated by Django 5.1 on 2024-08-24 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_options_chat_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('messages__created_at_date', 'messages__created_at_time')},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at_date', 'created_at_time')},
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
